scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus' # A URL que o Spring exp√µe
    static_configs:
      - targets: ['api-spring:8080']
    
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080'] #